# Generated by Django 3.1.2 on 2020-10-05 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainwindows', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stati',
            options={'verbose_name': 'Статьи', 'verbose_name_plural': 'Статьи'},
        ),
    ]
